#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <stdbool.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdlib.h>
#include <errno.h>
#include <crypt.h>
#include <ctype.h>
#include "./struc.h"
//#include "./admin-credentials.h"
#include "./constants.h"